# Generated by Django 5.0.7 on 2024-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_user_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='age',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
