# Generated by Django 5.0.7 on 2024-08-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_members_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AlterField(
            model_name='members',
            name='age',
            field=models.IntegerField(),
        ),
    ]
