# Generated by Django 5.0.7 on 2024-09-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_members_options_alter_members_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='members',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
    ]
