# Generated by Django 5.0.7 on 2024-09-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_slug_members_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75)),
                ('country', models.CharField(max_length=75)),
                ('member_id', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.members')),
            ],
        ),
    ]
