# Generated by Django 5.0.7 on 2024-09-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='members', to='posts.post'),
        ),
    ]
